### ISSUE TITLE
cdn_repo: support "for_hotfix" tag template feature

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/errata-tool-ansible#261]
Tag templates now have a new `for_hotfix` attribute. We need to support this. I'm thinking it will be another attribute on the tag template name, like we do today for the optional `variant` attribute.

_Currently supported:_
```yaml
    packages:
      rhceph-container:
        - latest
        - "{% raw %}{{version}}{% endraw %}"
        - "{% raw %}{{version}}-{{release}}{% endraw %}"
```

_Proposal, not yet supported:_
```yaml
    packages:
      rhceph-container:
        - latest
        - "{% raw %}{{version}}{% endraw %}"
        - "{% raw %}{{version}}-{{release}}{% endraw %}"
        - "{% raw %}{{version}}-{{hotfix}}-{{advisory}}{% endraw %}":
            is_hotfix: true
```
