### ISSUE TITLE
add_package_tag should support 'hotfix' boolean

### ISSUE THREAD

**Issue by oscrin** [ktdreyer/errata-tool-ansible#278]
https://github.com/ktdreyer/errata-tool-ansible/blob/master/library/errata_tool_cdn_repo.py#L329

Should support "Is hotfix?" boolean in Errata Tool.

**Comment by ktdreyer** [comment]
You're right, we should be able to add support for the `for_hotfix` boolean.

On my dev server, I see `/api/v1/cdn_repos/9999047` lists a `for_hotfix: true` or `for_hotfix: false` for all `cdn_repo_package_tags` entries now.

We'll need to make sure we can create and update these values, and then update all the methods in `errata_tool_cdn_repo.py` to do that.

**Comment by ktdreyer** [comment]
Currently playbook authors can define tags on packages like so:

```yaml
  errata_tool_cdn_repo:
    name: my-container
    release_type: Primary
    content_type: Docker
    variants: [AppStream-8.0.0]
    packages:
      test-container:
        - latest
```

Optionally, users can specify tags as dictionaries, like this:

```yaml
  errata_tool_cdn_repo:
    name: my-container
    release_type: Primary
    content_type: Docker
    variants: [AppStream-8.0.0]
    packages:
      test-container:
        - latest:
            variant: AppStream-8.0.0
```

We would extend this dictionary idea to take a new `has_hotfix` field:

```yaml
  errata_tool_cdn_repo:
    name: my-container
    release_type: Primary
    content_type: Docker
    variants: [AppStream-8.0.0]
    packages:
      test-container:
        - latest:
            has_hotfix: true
```
```
