### ISSUE TITLE
default parameters for errata_tool_user are not idempotent

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/errata-tool-ansible#80]
The following is not idempotent:

```yaml
- name: Add developer Errata Tool account
  errata_tool_user:
    login_name: cooldeveloper@redhat.com
    realname: Cool Developer
```

On the second run, Ansible says we're changing some things:
```
  - changing receives_mail from False to True
  - changing roles from [] to None
```
